apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoip-deployment
spec:
  selector:
    matchLabels:
      app: geoip
  template:
    metadata:
      labels:
        app: geoip
    spec:
      containers:
      - name: geoip
        image: bobloblaw/geoip
        ports:
        - containerPort: 8000
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: deployment-restart
spec:
  schedule: '*/3 * * * *' # every 3 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: deployment-restart
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command:
              - 'kubectl'
              - 'rollout'
              - 'restart'
              - 'deployment/geoip-deployment'
          restartPolicy: OnFailure
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: deployment-restart
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart
  namespace: default
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["geoip-deployment"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restart
subjects:
  - kind: ServiceAccount
    name: deployment-restart
    namespace: default